#!/usr/bin/env bash

selected=$({
  find ~/.config/ -mindepth 1 -maxdepth 1 -type d
  find ~/Herd/ -mindepth 1 -maxdepth 1 -type d
  find ~/Documents/codes/js -mindepth 1 -maxdepth 1 -type d
  find ~/Documents/codes/star-woss -mindepth 1 -maxdepth 1 -type d
  find ~/Documents/codes/learning -mindepth 1 -maxdepth 1 -type d
  find ~/Documents/codes/happydance -mindepth 1 -maxdepth 1 -type d
  find ~/Documents/codes/packages -mindepth 1 -maxdepth 1 -type d
  find ~/Documents/codes -mindepth 1 -maxdepth 1 -type d \
    ! -path "$HOME/Documents/codes/js" \
    ! -path "$HOME/Documents/codes/happydance/" \
    ! -path "$HOME/Documents/codes/packages/" \
    ! -path "$HOME/Documents/codes/star-woss"
} | while IFS= read -r fullpath; do
  [[ -z "$fullpath" || ! -d "$fullpath" ]] && continue
  relpath="${fullpath/#$HOME\/Documents\//}"
  [[ -n "$relpath" ]] && printf "%s\t%s\n" "$relpath" "$fullpath"
done | fzf --with-nth=1 --delimiter="\t" --ansi | cut -d$'\t' -f2 | sed 's/[[:space:]]*$//')

[[ -z "$selected" || ! -d "$selected" ]] && exit 0

selected_name=$(basename "$selected" | tr ".,: " "____")

switch_to() {
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t "$selected_name"
  else
    tmux switch-client -t "$selected_name"
  fi
}

if tmux has-session -t="$selected_name" 2>/dev/null; then
  switch_to
else
  tmux new-session -ds "$selected_name" -c "$selected"
  switch_to
fi
